version: "3.8"

services:
  recipe-backend:
    container_name: recipe-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000" # Only exposed internally to nginx
    env_file:
      - .env.prod
    restart: always
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  recipe-nginx:
    image: nginx:latest
    container_name: recipe-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html # ✅ THIS LINE IS MISSING

    depends_on:
      - recipe-backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
