name: Deploy to EC2

on:
  push:
    branches:
      - master # ✅ your actual branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/nginx-recipe-backend
            git pull origin master
            docker-compose down
            docker-compose up -d --build
